version: '3'
networks:
  canpatch_network:
    external: true
      
services:
  rabbitmq:
    image: 'rabbitmq:3-alpine'
    container_name: patrowlmanager-rabbitmq
    environment:
      - 'RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error}]'
    expose:
      - '5672'
    networks: 
      - canpatch_network

  db:
    image: 'postgres:11-alpine'
    restart: always
    container_name: patrowlmanager-postgres
    environment:
      - POSTGRES_DB=patrowl_db
      - POSTGRES_USER=PATROWL_DB_USER
      - POSTGRES_PASSWORD=PATROWL_DB_PASSWD_TO_CHANGE
    expose:
      - '5432'
    volumes:
      - './var/db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql'
    networks: 
      - canpatch_network

  web:
    container_name: patrowlmanager-django
    build: .
    image: 'patrowl/patrowl-manager-community-edition:${PATROWL_MANAGER_VERSION}'
    environment:
      - POSTGRES_HOST=db
      - DEBUG=True
      - 'RABBITMQ_HOSTNAME=rabbitmq:5672'
    depends_on:
      - db
      - rabbitmq
    expose:
      - '8003'
    volumes:
      - './staticfiles:/opt/patrowl-manager/staticfiles'
      - './media:/opt/patrowl-manager/media'
    links:
      - db
      - rabbitmq
    networks: 
      - canpatch_network

  nginx:
    image: 'nginx:stable-alpine'
    container_name: patrowlmanager-nginx
    ports:
      - '${FORWARD_WEB_PORT:-80}:8083'
    volumes:
      - './staticfiles:/opt/patrowl-manager/staticfiles'
      - './var/log:/opt/patrowl-manager/var/log'
      - './nginx_docker.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - web
    networks: 
      - canpatch_network
